Repository Smart-Grades/simple-grades, pull requests merged in 2023-06, with the labels that each got.

#21 feat: add Appwrite Web SDK and setup `.env` file for credentials
  .env.example
  nuxt.config.ts
  package-lock.json
  package.json
Labels: enhancement

#38 refactor: improve readability of the UI
  components/AccountPage.vue
  components/AuthLogin.vue
  components/AuthRegister.vue
  components/DashboardTable.vue
  components/DashboardTableNav.vue
  components/DashboardTableResult.vue
  components/Identification.vue
  pages/account.vue
  public/assets/css/main.css
  run-server
  tailwind.config.js
Labels: enhancement

#39 feat(Auth): add ability to sign up and in against appwrite
  app.vue
  components/AuthLogin.vue
  components/AuthRegister.vue
  middleware/auth.js
  nuxt.config.ts
  package-lock.json
  package.json
  pages/account.vue
  pages/auth.vue
  pages/dashboard.vue
  pages/ident.vue
  pages/logout.vue
  pages/verify.vue
Labels: enhancement

#44 feat(Introduction): add introduction for default course loading and completion flag
  .assets/fom/courses.json
  components/Identification.vue
  pages/ident.vue
Labels: enhancement

#46 feat(Account): add functionality for resetting courses with new uni major preset
  components/AccountConfirmModal.vue
  components/AccountPage.vue
Labels: enhancement

#48 feat: Add password recovery functionality
  components/AuthLogin.vue
  components/ResetPassword.vue
  components/RestoreEmail.vue
Labels: enhancement

#50 fix(Preset): increase course preset limit to 100
  components/AccountPage.vue
  components/Identification.vue
Labels: bug

#63 chore: Add macOS to .gitignore file
  .gitignore
Labels: enhancement

#45 feat(Dashboard): add functionality for viewing and adding courses
  components/AccountPage.vue
  components/DashboardTable.vue
  components/DashboardTableResult.vue
  pages/dashboard.vue
Labels: enhancement

#40 chore: bump v1.0.0
  .assets/fom/courses.json
  .env.example
  .gitignore
  app.vue
  components/AccountChangeAuth.vue
  components/AccountConfirmModal.vue
  components/AccountPage.vue
  components/AuthLogin.vue
  components/AuthRegister.vue
  components/DashboardTable.vue
  components/DashboardTableNav.vue
  components/DashboardTableResult.vue
  components/Identification.vue
  components/IndexHero.vue
  components/IndexSteps.vue
  components/ResetPassword.vue
  components/RestoreEmail.vue
  error.vue
  middleware/auth.js
  nuxt.config.ts
  package-lock.json
  package.json
  pages/account.vue
  pages/auth.vue
  pages/dashboard.vue
  pages/ident.vue
  pages/logout.vue
  pages/verify.vue
  public/assets/css/main.css
  public/assets/img/delete-icon.svg
  public/assets/img/logo.png
  public/favicon.ico
  run-server
  tailwind.config.js
Labels: enhancement

#70 fix(Dashboard): resolve issue with `vue-float-label` package
  components/DashboardTable.vue
  package-lock.json
  package.json
Labels: bug, branch/main
